name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: python version
      run: python --version
    - name: Install Sphinx
      run: sudo apt-get install python3-sphinx
    - name: Run pip install
      run: pip install -r requirements.txt
    - name: Run the build
      run: make html

